"""Audited migration-owned resources and conservative internal record lifecycle."""

from alos.domains.record_repository import RecordSpec
from alos.identity import Principal


def transition_visible(status: str, principal: Principal) -> bool:
    operational = (
        bool(principal.roles & {"DIVISION_LEAD", "DIVISION_MEMBER", "IT_ADMIN"})
        and "it.write" in principal.permissions
    )
    return operational and (
        status not in {"CLOSED", "REVIEWED"} or "DIVISION_LEAD" in principal.roles
    )


SPECS = {
    "systems": RecordSpec(
        "systems",
        "system_id",
        "ItSystem",
        "ACTIVE",
        {"ACTIVE": ("INACTIVE",), "INACTIVE": ("ACTIVE",)},
        frozenset(["criticality", "description", "name", "system_code"]),
        frozenset(["criticality", "description", "name", "system_code"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "integrations": RecordSpec(
        "integrations",
        "integration_id",
        "ItIntegration",
        "ACTIVE",
        {"ACTIVE": ("INACTIVE",), "INACTIVE": ("ACTIVE",)},
        frozenset(["endpoint_ref", "integration_type", "name", "system_id"]),
        frozenset(["endpoint_ref", "integration_type", "name"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "databases": RecordSpec(
        "databases",
        "database_id",
        "ItDatabase",
        "ACTIVE",
        {"ACTIVE": ("INACTIVE",), "INACTIVE": ("ACTIVE",)},
        frozenset(["classification", "engine", "environment", "name", "system_id"]),
        frozenset(["classification", "engine", "environment", "name"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "environments": RecordSpec(
        "environments",
        "environment_id",
        "ItEnvironment",
        "ACTIVE",
        {"ACTIVE": ("INACTIVE",), "INACTIVE": ("ACTIVE",)},
        frozenset(["base_url", "environment_type", "name"]),
        frozenset(["base_url", "environment_type", "name"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "repositories": RecordSpec(
        "repositories",
        "repository_id",
        "ItRepository",
        "ACTIVE",
        {"ACTIVE": ("INACTIVE",), "INACTIVE": ("ACTIVE",)},
        frozenset(["default_branch", "external_url", "name", "provider"]),
        frozenset(["default_branch", "external_url", "name", "provider"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "cicd_pipelines": RecordSpec(
        "cicd_pipelines",
        "pipeline_id",
        "ItCicdPipeline",
        "ACTIVE",
        {"ACTIVE": ("INACTIVE",), "INACTIVE": ("ACTIVE",)},
        frozenset(["name", "provider", "repository_id"]),
        frozenset(["name", "provider"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "ci_runs": RecordSpec(
        "ci_runs",
        "ci_run_id",
        "ItCiRun",
        None,
        {},
        frozenset(
            ["commit_sha", "external_run_id", "finished_at", "pipeline_id", "started_at", "status"]
        ),
        frozenset([]),
        True,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "releases": RecordSpec(
        "releases",
        "it_release_id",
        "ItRelease",
        "PLANNED",
        {
            "PLANNED": ("IN_REVIEW", "CANCELLED"),
            "IN_REVIEW": ("PLANNED", "CANCELLED"),
            "CANCELLED": (),
        },
        frozenset(["environment_id", "repository_id", "version"]),
        frozenset(["version"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "technical_debts": RecordSpec(
        "technical_debts",
        "technical_debt_id",
        "ItTechnicalDebt",
        "OPEN",
        {
            "OPEN": ("IN_PROGRESS",),
            "IN_PROGRESS": ("RESOLVED",),
            "RESOLVED": ("CLOSED",),
            "CLOSED": (),
        },
        frozenset(["description", "priority", "title"]),
        frozenset(["description", "priority", "title"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "service_monitors": RecordSpec(
        "service_monitors",
        "service_monitor_id",
        "ItServiceMonitor",
        None,
        {},
        frozenset(["check_type", "last_checked_at", "name", "status", "system_id", "target"]),
        frozenset([]),
        True,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "incidents": RecordSpec(
        "incidents",
        "incident_id",
        "ItIncident",
        "OPEN",
        {
            "OPEN": ("INVESTIGATING",),
            "INVESTIGATING": ("RESOLVED",),
            "RESOLVED": ("CLOSED",),
            "CLOSED": (),
        },
        frozenset(["description", "severity", "system_id", "title"]),
        frozenset(["description", "severity", "title"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "security_findings": RecordSpec(
        "security_findings",
        "security_finding_id",
        "ItSecurityFinding",
        "OPEN",
        {
            "OPEN": ("IN_REVIEW",),
            "IN_REVIEW": ("REMEDIATING",),
            "REMEDIATING": ("RESOLVED",),
            "RESOLVED": ("CLOSED",),
            "CLOSED": (),
        },
        frozenset(["description", "severity", "system_id", "title"]),
        frozenset(["description", "severity", "title"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "backup_policies": RecordSpec(
        "backup_policies",
        "backup_policy_id",
        "ItBackupPolicy",
        "ACTIVE",
        {"ACTIVE": ("INACTIVE",), "INACTIVE": ("ACTIVE",)},
        frozenset(["frequency", "name", "retention_days", "system_id"]),
        frozenset(["frequency", "name", "retention_days"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "backup_runs": RecordSpec(
        "backup_runs",
        "backup_run_id",
        "ItBackupRun",
        None,
        {},
        frozenset(["artifact_ref", "backup_policy_id", "finished_at", "started_at", "status"]),
        frozenset([]),
        True,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "restore_tests": RecordSpec(
        "restore_tests",
        "restore_test_id",
        "ItRestoreTest",
        None,
        {},
        frozenset(["backup_run_id", "notes", "result", "tested_at"]),
        frozenset([]),
        True,
        transition_authorized=transition_visible,
        status_field="status",
    ),
    "dr_plans": RecordSpec(
        "dr_plans",
        "dr_plan_id",
        "ItDrPlan",
        "ACTIVE",
        {"ACTIVE": ("INACTIVE",), "INACTIVE": ("ACTIVE",)},
        frozenset(["name", "rpo_minutes", "rto_minutes", "system_id"]),
        frozenset(["name", "rpo_minutes", "rto_minutes"]),
        False,
        transition_authorized=transition_visible,
        status_field="status",
    ),
}
